import axios from "axios";

export const langMap = {
  af: "Afrikaans",
  sq: "Albania",
  am: "Amharik",
  ar: "Arab",
  hy: "Armenia",
  az: "Azerbaijan",
  eu: "Bask",
  be: "Belarus",
  bn: "Bengali",
  bs: "Bosnia",
  bg: "Bulgaria",
  ca: "Katalan",
  ceb: "Cebuano",
  ny: "Chichewa",
  zh: "Mandarin (Sederhana)",
  "zh-TW": "Mandarin (Tradisional)",
  co: "Korsika",
  hr: "Kroasia",
  cs: "Ceko",
  da: "Denmark",
  nl: "Belanda",
  en: "Inggris",
  eo: "Esperanto",
  et: "Estonia",
  tl: "Filipina (Tagalog)",
  fi: "Finlandia",
  fr: "Prancis",
  fy: "Frisia",
  gl: "Galisia",
  ka: "Georgia",
  de: "Jerman",
  el: "Yunani",
  gu: "Gujarati",
  ht: "Kreol Haiti",
  ha: "Hausa",
  haw: "Hawaii",
  he: "Ibrani",
  hi: "Hindi",
  hmn: "Hmong",
  hu: "Hungaria",
  is: "Islandia",
  ig: "Igbo",
  id: "Indonesia",
  ga: "Irlandia",
  it: "Italia",
  ja: "Jepang",
  jw: "Jawa",
  kn: "Kannada",
  kk: "Kazakh",
  km: "Khmer",
  rw: "Kinyarwanda",
  ko: "Korea",
  ku: "Kurdi",
  ky: "Kirgis",
  la: "Latin",
  lv: "Latvia",
  lt: "Lithuania",
  lb: "Luksemburg",
  mk: "Makedonia",
  mg: "Malagasi",
  ms: "Melayu",
  ml: "Malayalam",
  mt: "Malta",
  mi: "Maori",
  mr: "Marathi",
  mn: "Mongolia",
  my: "Burma (Myanmar)",
  ne: "Nepali",
  no: "Norwegia",
  or: "Odia",
  ps: "Pashto",
  fa: "Persia",
  pl: "Polandia",
  pt: "Portugis",
  pa: "Punjabi",
  ro: "Rumania",
  ru: "Rusia",
  sm: "Samoa",
  gd: "Gaelik Skotlandia",
  sr: "Serbia",
  st: "Sesotho",
  sn: "Shona",
  sd: "Sindhi",
  si: "Sinhala",
  sk: "Slowakia",
  sl: "Slovenia",
  so: "Somalia",
  es: "Spanyol",
  su: "Sunda",
  sw: "Swahili",
  sv: "Swedia",
  tg: "Tajik",
  ta: "Tamil",
  tt: "Tatar",
  te: "Telugu",
  th: "Thailand",
  tr: "Turki",
  tk: "Turkmen",
  uk: "Ukraina",
  ur: "Urdu",
  ug: "Uighur",
  uz: "Uzbek",
  vi: "Vietnam",
  cy: "Wales",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  zu: "Zulu",
};

export async function translateText(text, to = "id", from = "auto") {
  if (!text || typeof text !== "string") throw new Error("Teks tidak boleh kosong.");

  const { data } = await axios.get("https://translate.googleapis.com/translate_a/single", {
    params: {
      client: "gtx",
      sl: from,
      tl: to,
      dt: "t",
      q: text,
    },
  });

  const result = data[0]
    ?.map((s) => s?.[0])
    .filter(Boolean)
    .join("");

  const detectedLang = data[2] || from;

  return {
    result,
    detectedLang,
    sourceLangName: langMap[detectedLang] || detectedLang,
    targetLangName: langMap[to] || to,
  };
}